package com.vinicius.bosh.controller.handler;

import com.vinicius.bosh.model.Appliance;
import com.vinicius.bosh.service.SubscriptionService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.reactive.function.server.RouterFunction;
import org.springframework.web.reactive.function.server.RouterFunctions;
import org.springframework.web.reactive.function.server.ServerResponse;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Sinks;

import static org.springframework.web.reactive.function.server.RequestPredicates.GET;

@Configuration
public class RequestRouter {
    //TODO need to be improved to filter onlu the status generated by the Producer.
    @Autowired
    private SubscriptionService subscriptionService;

    private final Sinks.Many<Appliance> eventSink = Sinks.many().multicast().directBestEffort();


    public Flux<String> getRoute(){

        return subscriptionService.findURLByEvenType(eventSink.asFlux()
                .map(Appliance::getStatus));
    }

    @Bean
    RouterFunction<ServerResponse> routes(RequestHandler requestHandler) {
        getRoute();
        return RouterFunctions
                .route(GET("/appliancestream/"), requestHandler::streamApplianceStatus);
    }
}