openapi: 3.0.3

components:
  schemas:
    ApplianceFail:
      type: object
      properties:
        message:
          type: string
          example: Some event happened
      required:
        - message